export interface Hackathon {
  id: string
  title: string
  organizer: string
  description: string
  fullDescription: string
  prize: string
  participants: number
  daysLeft: number
  status: "open" | "closing-soon" | "ended"
  mode: "online" | "in-person" | "hybrid"
  level: "beginner" | "intermediate" | "advanced" | "all"
  domain: string
  image: string
  techStack: string[]
  startDate: string
  endDate: string
  eligibility: string
  teamSize: { min: number; max: number }
}

export const hackathons: Hackathon[] = [
  {
    id: "1",
    title: "AI Innovation Challenge",
    organizer: "TechCorp",
    description: "Build the next generation of AI-powered applications that solve real-world problems.",
    fullDescription: "Join thousands of developers in creating cutting-edge AI solutions. This hackathon focuses on practical applications of machine learning, natural language processing, and computer vision to address challenges in healthcare, education, and sustainability. Participants will have access to mentorship from industry experts, cloud computing credits, and exclusive workshops.",
    prize: "$50,000",
    participants: 1234,
    daysLeft: 12,
    status: "open",
    mode: "online",
    level: "all",
    domain: "AI/ML",
    image: "https://images.unsplash.com/photo-1677442d019cecf8025246d34ac432ae52f19a70b27191fd21650e3cb014e56?w=400&h=200&fit=crop",
    techStack: ["Python", "TensorFlow", "PyTorch", "OpenAI API"],
    startDate: "2026-02-15",
    endDate: "2026-02-28",
    eligibility: "Open to all developers worldwide",
    teamSize: { min: 1, max: 5 },
  },
  {
    id: "2",
    title: "Web3 Builders Summit",
    organizer: "BlockChain Labs",
    description: "Create decentralized applications that push the boundaries of blockchain technology.",
    fullDescription: "Explore the future of decentralized finance, NFTs, and smart contracts. Build innovative solutions on Ethereum, Solana, or other blockchain platforms that reimagine how we interact with digital assets. Top projects may receive funding opportunities from our VC partners.",
    prize: "$25,000",
    participants: 856,
    daysLeft: 5,
    status: "closing-soon",
    mode: "hybrid",
    level: "intermediate",
    domain: "Web3",
    image: "https://images.unsplash.com/photo-1639762681033-6461ffad8d80?w=400&h=200&fit=crop",
    techStack: ["Solidity", "Rust", "Ethers.js", "Hardhat"],
    startDate: "2026-02-01",
    endDate: "2026-02-10",
    eligibility: "Developers with blockchain experience preferred",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: "3",
    title: "Green Tech Hackathon",
    organizer: "EcoFuture Foundation",
    description: "Develop sustainable solutions to combat climate change and environmental challenges.",
    fullDescription: "Use technology to create a more sustainable future. Projects can range from carbon footprint trackers to renewable energy optimization tools. Mentorship from environmental scientists and sustainability experts included. Winning projects may be piloted by partner organizations.",
    prize: "$30,000",
    participants: 2100,
    daysLeft: 20,
    status: "open",
    mode: "in-person",
    level: "beginner",
    domain: "Sustainability",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=200&fit=crop",
    techStack: ["React", "Node.js", "IoT", "Data Visualization"],
    startDate: "2026-03-01",
    endDate: "2026-03-15",
    eligibility: "Students and early-career developers",
    teamSize: { min: 3, max: 6 },
  },
  {
    id: "4",
    title: "FinTech Revolution",
    organizer: "Global Finance Inc",
    description: "Revolutionize the financial industry with innovative payment and banking solutions.",
    fullDescription: "Design the future of finance with solutions for digital payments, investment platforms, or financial inclusion. Access to real financial APIs, sandbox environments, and datasets provided. Connect with leaders from top financial institutions.",
    prize: "$75,000",
    participants: 1567,
    daysLeft: 8,
    status: "open",
    mode: "online",
    level: "advanced",
    domain: "FinTech",
    image: "https://images.unsplash.com/photo-1563986768611-b3f3de2c88b0?w=400&h=200&fit=crop",
    techStack: ["TypeScript", "Next.js", "Plaid API", "Stripe"],
    startDate: "2026-02-10",
    endDate: "2026-02-20",
    eligibility: "Professional developers with financial sector experience",
    teamSize: { min: 2, max: 5 },
  },
  {
    id: "5",
    title: "Healthcare Innovation Sprint",
    organizer: "MedTech Alliance",
    description: "Build solutions that improve patient care and healthcare accessibility worldwide.",
    fullDescription: "Create digital health tools that make healthcare more accessible and effective. From telemedicine platforms to health monitoring apps, your innovation could save lives. HIPAA compliance guidelines and mentorship provided.",
    prize: "$40,000",
    participants: 945,
    daysLeft: 3,
    status: "closing-soon",
    mode: "online",
    level: "all",
    domain: "Healthcare",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["React Native", "FHIR API", "AWS", "Python"],
    startDate: "2026-01-25",
    endDate: "2026-02-05",
    eligibility: "Open to all, healthcare professionals encouraged",
    teamSize: { min: 1, max: 4 },
  },
  {
    id: "6",
    title: "Mobile App Masters",
    organizer: "AppDev Community",
    description: "Design and develop mobile applications that enhance everyday life experiences.",
    fullDescription: "Create the next must-have mobile app. Whether it's productivity, entertainment, or social good, show us your vision for mobile experiences that users will love. App store credits and marketing support for winning projects.",
    prize: "$20,000",
    participants: 1890,
    daysLeft: 15,
    status: "open",
    mode: "online",
    level: "beginner",
    domain: "Mobile",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["React Native", "Flutter", "Swift", "Kotlin"],
    startDate: "2026-02-20",
    endDate: "2026-03-05",
    eligibility: "First-time hackathon participants welcome",
    teamSize: { min: 1, max: 3 },
  },
  {
    id: "7",
    title: "Cybersecurity Challenge",
    organizer: "SecureNet Labs",
    description: "Strengthen digital security by building tools to protect against cyber threats.",
    fullDescription: "Develop security solutions ranging from threat detection systems to privacy-preserving technologies. Capture-the-flag challenges and security workshops included. Top performers may receive job offers from partner companies.",
    prize: "$60,000",
    participants: 678,
    daysLeft: 0,
    status: "ended",
    mode: "hybrid",
    level: "advanced",
    domain: "Security",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Python", "Go", "Rust", "Wireshark"],
    startDate: "2026-01-10",
    endDate: "2026-01-20",
    eligibility: "Security professionals and enthusiasts",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: "8",
    title: "EdTech Innovation Lab",
    organizer: "LearnForward",
    description: "Transform education with technology solutions that make learning accessible to all.",
    fullDescription: "Build educational tools that democratize learning. From AI tutors to gamified learning platforms, help create the future of education for students worldwide. Partnerships with schools and universities for pilot programs available.",
    prize: "$35,000",
    participants: 1120,
    daysLeft: 18,
    status: "open",
    mode: "online",
    level: "intermediate",
    domain: "EdTech",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Vue.js", "Firebase", "WebRTC", "GPT-4"],
    startDate: "2026-02-25",
    endDate: "2026-03-10",
    eligibility: "Educators and developers",
    teamSize: { min: 2, max: 5 },
  },
  {
    id: "9",
    title: "Cloud Native Challenge",
    organizer: "CloudScale Technologies",
    description: "Build scalable, resilient applications using cloud-native architectures.",
    fullDescription: "Design and implement applications that leverage the full power of cloud computing. Focus on microservices, containerization, and serverless patterns. Free cloud credits and architecture reviews from experts included.",
    prize: "$45,000",
    participants: 890,
    daysLeft: 14,
    status: "open",
    mode: "online",
    level: "advanced",
    domain: "Cloud",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Kubernetes", "Docker", "Terraform", "AWS/GCP/Azure"],
    startDate: "2026-02-18",
    endDate: "2026-03-04",
    eligibility: "DevOps engineers and cloud architects",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: "10",
    title: "Gaming & Metaverse Jam",
    organizer: "GameDev Studios",
    description: "Create immersive gaming experiences and metaverse applications.",
    fullDescription: "Build the next generation of interactive entertainment. From traditional games to VR/AR experiences and metaverse applications. Access to game engines, 3D assets, and mentorship from industry veterans.",
    prize: "$55,000",
    participants: 1456,
    daysLeft: 10,
    status: "open",
    mode: "hybrid",
    level: "intermediate",
    domain: "Gaming",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Unity", "Unreal Engine", "Three.js", "WebXR"],
    startDate: "2026-02-12",
    endDate: "2026-02-25",
    eligibility: "Game developers and 3D artists",
    teamSize: { min: 2, max: 6 },
  },
  {
    id: "11",
    title: "Social Impact Hackathon",
    organizer: "Nonprofits United",
    description: "Build technology solutions that address pressing social challenges.",
    fullDescription: "Create applications that make a real difference in communities. Focus areas include poverty reduction, accessibility, disaster response, and community building. Nonprofit partnerships available for winning solutions.",
    prize: "$25,000",
    participants: 734,
    daysLeft: 22,
    status: "open",
    mode: "online",
    level: "beginner",
    domain: "Social Good",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["React", "Node.js", "MongoDB", "Twilio"],
    startDate: "2026-03-05",
    endDate: "2026-03-20",
    eligibility: "Open to all with passion for social impact",
    teamSize: { min: 2, max: 5 },
  },
  {
    id: "12",
    title: "IoT Smart City Challenge",
    organizer: "Urban Innovation Lab",
    description: "Design IoT solutions that make cities smarter and more sustainable.",
    fullDescription: "Build connected devices and systems that improve urban living. From traffic optimization to waste management and energy efficiency. Hardware kits provided and smart city testbed access included.",
    prize: "$38,000",
    participants: 567,
    daysLeft: 16,
    status: "open",
    mode: "in-person",
    level: "intermediate",
    domain: "IoT",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Arduino", "Raspberry Pi", "MQTT", "Python"],
    startDate: "2026-02-22",
    endDate: "2026-03-08",
    eligibility: "Hardware enthusiasts and embedded developers",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: "13",
    title: "Data Science Olympics",
    organizer: "Analytics Pro",
    description: "Compete in data challenges and build predictive models with real-world datasets.",
    fullDescription: "Test your data science skills across multiple challenges including classification, regression, NLP, and computer vision. Access to premium datasets and computing resources. Top performers get interviews with data teams at partner companies.",
    prize: "$42,000",
    participants: 1678,
    daysLeft: 7,
    status: "open",
    mode: "online",
    level: "advanced",
    domain: "Data Science",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Python", "Pandas", "Scikit-learn", "Jupyter"],
    startDate: "2026-02-08",
    endDate: "2026-02-18",
    eligibility: "Data scientists and ML engineers",
    teamSize: { min: 1, max: 3 },
  },
  {
    id: "14",
    title: "E-commerce Innovation Fest",
    organizer: "RetailTech Consortium",
    description: "Reimagine the online shopping experience with innovative solutions.",
    fullDescription: "Build the future of e-commerce with solutions for personalization, AR try-on, checkout optimization, or logistics. Access to real transaction data and e-commerce APIs. Pilot opportunities with major retailers.",
    prize: "$48,000",
    participants: 923,
    daysLeft: 11,
    status: "open",
    mode: "online",
    level: "all",
    domain: "E-commerce",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Next.js", "Shopify API", "Stripe", "Algolia"],
    startDate: "2026-02-14",
    endDate: "2026-02-27",
    eligibility: "Full-stack developers and designers",
    teamSize: { min: 2, max: 5 },
  },
  {
    id: "15",
    title: "DevTools Builder",
    organizer: "Developer Experience Co",
    description: "Create tools that make developers more productive and happier.",
    fullDescription: "Build developer tools including CLI tools, IDE extensions, testing frameworks, or documentation generators. The best tools may be featured in popular developer newsletters and communities.",
    prize: "$32,000",
    participants: 456,
    daysLeft: 19,
    status: "open",
    mode: "online",
    level: "intermediate",
    domain: "DevTools",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["TypeScript", "Rust", "Go", "VSCode API"],
    startDate: "2026-02-28",
    endDate: "2026-03-12",
    eligibility: "Experienced developers who love building tools",
    teamSize: { min: 1, max: 3 },
  },
  {
    id: "16",
    title: "Voice & Conversational AI",
    organizer: "VoiceTech Labs",
    description: "Build voice-first applications and conversational experiences.",
    fullDescription: "Create voice assistants, chatbots, and conversational interfaces that feel natural and helpful. Access to voice APIs, NLU platforms, and user testing pools. Partnership opportunities with smart speaker manufacturers.",
    prize: "$36,000",
    participants: 612,
    daysLeft: 13,
    status: "open",
    mode: "online",
    level: "intermediate",
    domain: "AI/ML",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Dialogflow", "Amazon Lex", "Rasa", "Whisper API"],
    startDate: "2026-02-16",
    endDate: "2026-03-01",
    eligibility: "NLP enthusiasts and conversational designers",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: "17",
    title: "Accessibility Champions",
    organizer: "Inclusive Tech Foundation",
    description: "Build technology that makes the digital world accessible to everyone.",
    fullDescription: "Create solutions that break down barriers for people with disabilities. Focus on assistive technologies, accessible web apps, and inclusive design. Workshops with accessibility experts and user testing with diverse ability groups.",
    prize: "$28,000",
    participants: 389,
    daysLeft: 21,
    status: "open",
    mode: "hybrid",
    level: "beginner",
    domain: "Accessibility",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["React", "ARIA", "Screen Readers", "Voice Control"],
    startDate: "2026-03-03",
    endDate: "2026-03-17",
    eligibility: "Developers passionate about inclusive design",
    teamSize: { min: 2, max: 5 },
  },
  {
    id: "18",
    title: "Quantum Computing Quest",
    organizer: "QuantumTech Institute",
    description: "Explore quantum computing and build applications for quantum devices.",
    fullDescription: "Learn quantum computing fundamentals and build applications using real quantum hardware. Tutorials from quantum researchers, access to quantum simulators and IBM/Google quantum computers.",
    prize: "$65,000",
    participants: 234,
    daysLeft: 25,
    status: "open",
    mode: "online",
    level: "advanced",
    domain: "Quantum",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Qiskit", "Cirq", "Python", "Linear Algebra"],
    startDate: "2026-03-10",
    endDate: "2026-03-25",
    eligibility: "Physics/CS backgrounds preferred",
    teamSize: { min: 1, max: 3 },
  },
  {
    id: "19",
    title: "AgriTech Innovation Hub",
    organizer: "FarmTech Alliance",
    description: "Modernize agriculture with technology solutions for farmers.",
    fullDescription: "Build applications that help farmers increase yields, reduce waste, and adapt to climate change. Drone data, satellite imagery, and agricultural datasets provided. Pilot programs with farming cooperatives available.",
    prize: "$33,000",
    participants: 445,
    daysLeft: 17,
    status: "open",
    mode: "in-person",
    level: "all",
    domain: "AgriTech",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Python", "Computer Vision", "IoT", "React Native"],
    startDate: "2026-02-24",
    endDate: "2026-03-09",
    eligibility: "Developers interested in agriculture",
    teamSize: { min: 2, max: 5 },
  },
  {
    id: "20",
    title: "Music & Audio Tech Jam",
    organizer: "SoundWave Studios",
    description: "Create innovative music technology and audio applications.",
    fullDescription: "Build music creation tools, audio processing apps, or music discovery platforms. Access to audio APIs, sample libraries, and collaboration opportunities with musicians. Demo opportunities at music tech conferences.",
    prize: "$29,000",
    participants: 567,
    daysLeft: 9,
    status: "open",
    mode: "online",
    level: "intermediate",
    domain: "Music Tech",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Web Audio API", "Tone.js", "Python", "MIDI"],
    startDate: "2026-02-11",
    endDate: "2026-02-23",
    eligibility: "Musicians and audio developers",
    teamSize: { min: 1, max: 4 },
  },
  {
    id: "21",
    title: "Legal Tech Disrupt",
    organizer: "LawTech Innovators",
    description: "Transform the legal industry with technology solutions.",
    fullDescription: "Build applications that make legal services more accessible and efficient. From contract analysis to legal research tools. Mentorship from legal tech entrepreneurs and law firm partners.",
    prize: "$44,000",
    participants: 312,
    daysLeft: 6,
    status: "closing-soon",
    mode: "online",
    level: "intermediate",
    domain: "LegalTech",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["NLP", "Python", "React", "Elasticsearch"],
    startDate: "2026-02-05",
    endDate: "2026-02-15",
    eligibility: "Developers with interest in legal domain",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: "22",
    title: "Travel & Hospitality Hack",
    organizer: "TravelTech Global",
    description: "Reinvent travel experiences with innovative technology.",
    fullDescription: "Create solutions for travel planning, booking experiences, or sustainable tourism. Access to travel APIs, hotel data, and flight information. Partnerships with travel companies for winning solutions.",
    prize: "$37,000",
    participants: 678,
    daysLeft: 0,
    status: "ended",
    mode: "hybrid",
    level: "all",
    domain: "Travel",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["React", "GraphQL", "Maps API", "Node.js"],
    startDate: "2026-01-15",
    endDate: "2026-01-28",
    eligibility: "Travel enthusiasts and developers",
    teamSize: { min: 2, max: 5 },
  },
  {
    id: "23",
    title: "HR Tech Future",
    organizer: "WorkForce Innovations",
    description: "Build the future of work with HR technology solutions.",
    fullDescription: "Create tools for recruitment, employee engagement, performance management, or workplace collaboration. Focus on remote work challenges and the future of hybrid teams. Pilot opportunities with enterprise partners.",
    prize: "$39,000",
    participants: 423,
    daysLeft: 23,
    status: "open",
    mode: "online",
    level: "intermediate",
    domain: "HR Tech",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Next.js", "AI/ML", "Slack API", "GraphQL"],
    startDate: "2026-03-08",
    endDate: "2026-03-22",
    eligibility: "HR professionals and developers",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: "24",
    title: "Sports Analytics Challenge",
    organizer: "SportsTech League",
    description: "Apply data science to sports for better insights and predictions.",
    fullDescription: "Build sports analytics tools, fantasy sports applications, or fan engagement platforms. Access to historical sports data, real-time feeds, and video analysis tools. Collaboration opportunities with sports teams.",
    prize: "$46,000",
    participants: 789,
    daysLeft: 4,
    status: "closing-soon",
    mode: "online",
    level: "all",
    domain: "Sports Tech",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Python", "TensorFlow", "D3.js", "PostgreSQL"],
    startDate: "2026-01-28",
    endDate: "2026-02-08",
    eligibility: "Sports fans and data enthusiasts",
    teamSize: { min: 1, max: 4 },
  },
  {
    id: "25",
    title: "Insurance Innovation Lab",
    organizer: "InsurTech Consortium",
    description: "Modernize insurance with technology and data-driven solutions.",
    fullDescription: "Build applications for claims processing, risk assessment, or customer experience. Access to insurance datasets and actuarial guidance. Accelerator opportunities for promising startups.",
    prize: "$52,000",
    participants: 356,
    daysLeft: 15,
    status: "open",
    mode: "online",
    level: "advanced",
    domain: "InsurTech",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Python", "Machine Learning", "React", "AWS"],
    startDate: "2026-02-20",
    endDate: "2026-03-05",
    eligibility: "FinTech developers and data scientists",
    teamSize: { min: 2, max: 5 },
  },
  {
    id: "26",
    title: "Real Estate Tech",
    organizer: "PropTech Ventures",
    description: "Transform real estate with innovative property technology.",
    fullDescription: "Build solutions for property search, virtual tours, real estate analytics, or property management. Access to MLS data, 3D scanning technology, and real estate market APIs.",
    prize: "$41,000",
    participants: 534,
    daysLeft: 12,
    status: "open",
    mode: "hybrid",
    level: "intermediate",
    domain: "PropTech",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["React", "Three.js", "Node.js", "Maps API"],
    startDate: "2026-02-15",
    endDate: "2026-02-28",
    eligibility: "Full-stack developers and real estate professionals",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: "27",
    title: "Food & Nutrition Tech",
    organizer: "FoodTech Alliance",
    description: "Innovate in food technology, nutrition, and sustainable food systems.",
    fullDescription: "Build applications for meal planning, nutrition tracking, food waste reduction, or sustainable food sourcing. Partnerships with food companies and nutrition experts for winning solutions.",
    prize: "$27,000",
    participants: 623,
    daysLeft: 20,
    status: "open",
    mode: "online",
    level: "beginner",
    domain: "FoodTech",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["React Native", "Python", "Computer Vision", "Firebase"],
    startDate: "2026-03-01",
    endDate: "2026-03-15",
    eligibility: "Developers passionate about food and health",
    teamSize: { min: 1, max: 4 },
  },
  {
    id: "28",
    title: "Robotics & Automation",
    organizer: "RoboTech Labs",
    description: "Build the next generation of robots and automated systems.",
    fullDescription: "Create robotic applications from warehouse automation to service robots. Access to robot simulators, ROS documentation, and hardware kits. Demo opportunities at robotics conferences.",
    prize: "$58,000",
    participants: 345,
    daysLeft: 0,
    status: "ended",
    mode: "in-person",
    level: "advanced",
    domain: "Robotics",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["ROS", "Python", "C++", "Computer Vision"],
    startDate: "2026-01-05",
    endDate: "2026-01-18",
    eligibility: "Robotics engineers and embedded developers",
    teamSize: { min: 2, max: 5 },
  },
  {
    id: "29",
    title: "Mental Health Tech",
    organizer: "Wellness Innovations",
    description: "Build technology solutions that support mental health and wellness.",
    fullDescription: "Create applications for mental health support, meditation, stress management, or therapy access. Guidance from mental health professionals and privacy-first design workshops.",
    prize: "$34,000",
    participants: 489,
    daysLeft: 18,
    status: "open",
    mode: "online",
    level: "all",
    domain: "Healthcare",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["React", "Node.js", "AI/ML", "HIPAA Compliance"],
    startDate: "2026-02-25",
    endDate: "2026-03-10",
    eligibility: "Developers interested in mental health",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: "30",
    title: "Supply Chain Innovation",
    organizer: "LogiTech Global",
    description: "Optimize supply chains with technology and data analytics.",
    fullDescription: "Build solutions for inventory management, logistics optimization, or supply chain transparency. Access to supply chain datasets, IoT sensors, and blockchain infrastructure.",
    prize: "$47,000",
    participants: 412,
    daysLeft: 14,
    status: "open",
    mode: "online",
    level: "intermediate",
    domain: "Logistics",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Python", "Blockchain", "IoT", "React"],
    startDate: "2026-02-18",
    endDate: "2026-03-03",
    eligibility: "Supply chain professionals and developers",
    teamSize: { min: 2, max: 5 },
  },
  {
    id: "31",
    title: "Energy Tech Challenge",
    organizer: "CleanEnergy Labs",
    description: "Accelerate the transition to clean energy with technology.",
    fullDescription: "Build applications for renewable energy optimization, smart grid management, or energy efficiency. Access to energy consumption data and smart meter APIs. Partnerships with utility companies.",
    prize: "$51,000",
    participants: 378,
    daysLeft: 24,
    status: "open",
    mode: "hybrid",
    level: "intermediate",
    domain: "Energy",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Python", "IoT", "Machine Learning", "React"],
    startDate: "2026-03-08",
    endDate: "2026-03-22",
    eligibility: "Energy sector professionals and developers",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: "32",
    title: "Fashion Tech Runway",
    organizer: "StyleTech Studios",
    description: "Innovate at the intersection of fashion and technology.",
    fullDescription: "Build solutions for virtual try-on, sustainable fashion, personalized styling, or fashion supply chain. Access to fashion datasets, AR tools, and industry mentorship.",
    prize: "$31,000",
    participants: 567,
    daysLeft: 11,
    status: "open",
    mode: "online",
    level: "all",
    domain: "Fashion Tech",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["React", "AR.js", "TensorFlow", "Node.js"],
    startDate: "2026-02-13",
    endDate: "2026-02-26",
    eligibility: "Fashion enthusiasts and developers",
    teamSize: { min: 2, max: 5 },
  },
  {
    id: "33",
    title: "Government & Civic Tech",
    organizer: "CivicTech Alliance",
    description: "Build technology that improves government services and civic engagement.",
    fullDescription: "Create solutions for citizen services, open data visualization, or civic participation. Partnerships with government agencies for pilot programs. Focus on transparency and accessibility.",
    prize: "$26,000",
    participants: 289,
    daysLeft: 19,
    status: "open",
    mode: "online",
    level: "beginner",
    domain: "Civic Tech",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["React", "Python", "Open Data APIs", "D3.js"],
    startDate: "2026-02-27",
    endDate: "2026-03-12",
    eligibility: "Citizens passionate about civic improvement",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: "34",
    title: "Space Tech Frontier",
    organizer: "AeroSpace Innovations",
    description: "Build technology for space exploration and satellite applications.",
    fullDescription: "Create applications using satellite data, space weather monitoring, or mission planning tools. Access to NASA APIs, satellite imagery, and mentorship from aerospace engineers.",
    prize: "$72,000",
    participants: 234,
    daysLeft: 26,
    status: "open",
    mode: "online",
    level: "advanced",
    domain: "Space Tech",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Python", "Julia", "Satellite APIs", "3D Visualization"],
    startDate: "2026-03-12",
    endDate: "2026-03-28",
    eligibility: "Aerospace enthusiasts and developers",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: "35",
    title: "Startup Weekend Hack",
    organizer: "Entrepreneur Hub",
    description: "Turn your startup idea into a working prototype in 48 hours.",
    fullDescription: "The classic startup hackathon format - pitch ideas, form teams, build prototypes, and present to investors. Mentorship from successful founders and investors. Funding opportunities for promising teams.",
    prize: "$100,000",
    participants: 1234,
    daysLeft: 8,
    status: "open",
    mode: "in-person",
    level: "all",
    domain: "Startup",
    image: "/placeholder.svg?height=200&width=400",
    techStack: ["Any", "MVP Focus", "Pitch Deck", "Demo"],
    startDate: "2026-02-10",
    endDate: "2026-02-12",
    eligibility: "Aspiring entrepreneurs and builders",
    teamSize: { min: 3, max: 6 },
  },
]

export const domains = [
  "All",
  "AI/ML",
  "Web3",
  "Sustainability",
  "FinTech",
  "Healthcare",
  "Mobile",
  "Security",
  "EdTech",
  "Cloud",
  "Gaming",
  "Social Good",
  "IoT",
  "Data Science",
  "E-commerce",
  "DevTools",
  "Accessibility",
  "Quantum",
  "AgriTech",
  "Music Tech",
  "LegalTech",
  "Travel",
  "HR Tech",
  "Sports Tech",
  "InsurTech",
  "PropTech",
  "FoodTech",
  "Robotics",
  "Logistics",
  "Energy",
  "Fashion Tech",
  "Civic Tech",
  "Space Tech",
  "Startup",
]

export const modes = ["All", "Online", "In-Person", "Hybrid"]
export const levels = ["All", "Beginner", "Intermediate", "Advanced"]
export const statuses = ["All", "Open", "Closing Soon", "Ended"]

export function getHackathonById(id: string): Hackathon | undefined {
  return hackathons.find((h) => h.id === id)
}

export function searchHackathons(query: string): Hackathon[] {
  const lowerQuery = query.toLowerCase()
  return hackathons.filter(
    (h) =>
      h.title.toLowerCase().includes(lowerQuery) ||
      h.description.toLowerCase().includes(lowerQuery) ||
      h.techStack.some((tech) => tech.toLowerCase().includes(lowerQuery)) ||
      h.domain.toLowerCase().includes(lowerQuery)
  )
}
